"""Dumps reference values of the circular families for the C++ golden tests.

Run from the repo root: ``python3 tools/circulas/dump_golden.py OUT.json``
for a JSON file, or ``python3 tools/circulas/dump_golden.py --cpp`` to
regenerate ``test/src_test/include/circular_golden.hpp``, which embeds the
same JSON as a string literal for the C++ golden tests. For each family, parameter point, and rotation, the file records the density,
CDF, both h-functions, and both inverse h-functions on a fixed lattice of
arguments, plus Kendall's tau by numerical integration. The parameter lattice
covers interiors; near-boundary points carry an ``_edge`` suffix, following
the convention of ``scripts/README.md``.
"""
import json
import sys
import numpy as np
from scipy import integrate

import circulas as cc

ARGS = np.array([0.02, 0.5, 0.98])
U, V = [x.ravel() for x in np.meshgrid(ARGS, ARGS, indexing="ij")]
W = np.array([0.05, 0.5, 0.95])

BINDING_PARAMS = {
    "cardioid": {"interior": [(0.2, 0.0), (0.4, 1.0), (0.3, -2.5)], "edge": [(0.5, 3.0), (0.0, 0.0)]},
    "wrapped_cauchy": {"interior": [(0.3, 0.0), (0.7, 1.0), (0.5, np.pi)], "edge": [(0.99, -3.0), (0.0, 0.0)]},
    "von_mises": {"interior": [(1.0, 0.0), (4.0, 1.0), (2.0, np.pi)], "edge": [(100.0, 0.5), (0.0, 0.0)]},
}
SECTIONS_PARAMS = {
    "quad_sections": {"interior": [(0.5, 0.5, 0.0), (0.8, 0.8, 1.0), (0.3, 0.3, -2.0)], "edge": [(1.0, 1.0, 3.0), (0.0, 0.0, 0.0)]},
    "cubic_sections": {"interior": [(0.5, -0.3, 0.0), (0.8, 0.6, 1.0), (0.3, -0.9, -2.0)], "edge": [(1.0, -1.0, 3.0), (1.0, 1.0, -1.0), (0.0, 0.0, 0.0)]},
}


def kendall_tau_numeric(h1, h2):
    """tau = 1 - 4 int int h1(v | u) h2(u | v) du dv."""
    val = integrate.dblquad(lambda v, u: h1(u, v) * h2(u, v), 0, 1, 0, 1, epsabs=1e-9)[0]
    return 1.0 - 4.0 * val


def binding_entry(Fam, par, mu, rotation):
    G = Fam(par)
    q, phase = (1, mu) if rotation == 0 else (-1, -mu)  # rotation 90 is q = -1 with phase -mu
    entry = {
        "parameters": [par, mu], "rotation": rotation, "u": U.tolist(), "v": V.tolist(), "w": W.tolist(),
        "pdf": cc.circula_pdf(G, q, phase, U, V).tolist(),
        "cdf": cc.circula_cdf(G, q, phase, U, V).tolist(),
        "hfunc1": cc.circula_hfunc1(G, q, phase, U, V).tolist(),
        "hfunc2": cc.circula_hfunc2(G, q, phase, U, V).tolist(),
        "hinv1": [cc.circula_hinv1(G, q, phase, U, w).tolist() for w in W],
        "hinv2": [cc.circula_hinv2(G, q, phase, V, w).tolist() for w in W],
        "tau": kendall_tau_numeric(lambda u, v: cc.circula_hfunc1(G, q, phase, u, v),
                                   lambda u, v: cc.circula_hfunc2(G, q, phase, u, v)),
    }
    return entry


def sections_entry(name, a, b, mu):
    return {
        "parameters": [a, mu] if name == "quad_sections" else [a, b, mu], "rotation": 0,
        "u": U.tolist(), "v": V.tolist(), "w": W.tolist(),
        "pdf": cc.sections_pdf(a, b, mu, U, V).tolist(),
        "cdf": cc.sections_cdf(a, b, mu, U, V).tolist(),
        "hfunc1": cc.sections_hfunc1(a, b, mu, U, V).tolist(),
        "hfunc2": cc.sections_hfunc2(a, b, mu, U, V).tolist(),
        "hinv1": [cc.sections_hinv1(a, b, mu, U, w).tolist() for w in W],
        "hinv2": [cc.sections_hinv2(a, b, mu, V, w).tolist() for w in W],
        "tau": cc.sections_kendall_tau(a, b, mu),
        "spearman": cc.sections_spearman_rho(a, b, mu),
    }


HEADER = """// Copyright © 2016-2026 Thomas Nagler and Thibault Vatter
//
// This file is part of the vinecopulib library and licensed under the terms of
// the MIT license. For a copy, see the LICENSE file in the root directory of
// vinecopulib or https://vinecopulib.github.io/vinecopulib/.

// Generated by tools/circulas/dump_golden.py --cpp; do not edit by hand.
// Reference values of the circular families computed independently of the
// library (see tools/circulas/README.md), embedded as JSON.

#pragma once

namespace test_circular_golden {

inline const char* json =
  R"golden(%s)golden";

} // namespace test_circular_golden
"""


def build():
    out = {"lattice_note": "u and v are the flattened 5 x 5 product of ARGS; hinv rows correspond to w"}
    for name, groups in BINDING_PARAMS.items():
        Fam = cc.FAMILIES[name]
        for suffix, points in (("", groups["interior"]), ("_edge", groups["edge"])):
            for rotation in (0, 90):
                out[f"{name}{suffix}_rot{rotation}"] = [binding_entry(Fam, par, mu, rotation) for par, mu in points]
    for name, groups in SECTIONS_PARAMS.items():
        for suffix, points in (("", groups["interior"]), ("_edge", groups["edge"])):
            out[f"{name}{suffix}"] = [sections_entry(name, a, b, mu) for a, b, mu in points]
    return out


def main(path):
    out = build()
    with open(path, "w") as fh:
        json.dump(out, fh, indent=1)
    print(f"wrote {path}: {sum(len(v) for v in out.values() if isinstance(v, list))} parameter points")


def main_cpp():
    import os
    out = build()
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "..", "..", "test", "src_test", "include", "circular_golden.hpp")
    with open(path, "w") as fh:
        fh.write(HEADER % json.dumps(out, separators=(",", ":")))
    print(f"wrote {os.path.relpath(path)}")


if __name__ == "__main__":
    if len(sys.argv) == 2 and sys.argv[1] == "--cpp":
        main_cpp()
    elif len(sys.argv) == 2:
        main(sys.argv[1])
    else:
        print(__doc__)
        sys.exit(2)
