var searchData=
[
  ['bicop_5ffamilies',['bicop_families',['../namespacevinecopulib_1_1bicop__families.html',1,'vinecopulib']]],
  ['vinecopulib_3a_20a_20c_2b_2b_20library_20for_20vine_20copula_20modeling',['vinecopulib: a C++ library for vine copula modeling',['../index.html',1,'']]],
  ['tools_5fstats',['tools_stats',['../namespacevinecopulib_1_1tools__stats.html',1,'vinecopulib']]],
  ['vinecop',['Vinecop',['../classvinecopulib_1_1_vinecop.html#a391541e2795d06a848d5a17fe3496a63',1,'vinecopulib::Vinecop::Vinecop(size_t d)'],['../classvinecopulib_1_1_vinecop.html#a9aa43135a9319e20573a72f01c82cd3b',1,'vinecopulib::Vinecop::Vinecop(const Eigen::Matrix&lt; size_t, Eigen::Dynamic, Eigen::Dynamic &gt; &amp;matrix, bool check_matrix=true)'],['../classvinecopulib_1_1_vinecop.html#a48f302a8c97dce27619b70aeb257fe96',1,'vinecopulib::Vinecop::Vinecop(const std::vector&lt; std::vector&lt; Bicop &gt;&gt; &amp;pair_copulas, const Eigen::Matrix&lt; size_t, Eigen::Dynamic, Eigen::Dynamic &gt; &amp;matrix, bool check_matrix=true)'],['../classvinecopulib_1_1_vinecop.html#a1bba8d207a21b5d0c76660af40383822',1,'vinecopulib::Vinecop::Vinecop(const Eigen::MatrixXd &amp;data, FitControlsVinecop controls=FitControlsVinecop())'],['../classvinecopulib_1_1_vinecop.html#aa38ebdd3582482fad7d1ace027a9c162',1,'vinecopulib::Vinecop::Vinecop(const Eigen::MatrixXd &amp;data, const Eigen::Matrix&lt; size_t, Eigen::Dynamic, Eigen::Dynamic &gt; &amp;matrix, FitControlsVinecop controls=FitControlsVinecop(), bool check_matrix=true)'],['../classvinecopulib_1_1_vinecop.html#ad6ab9327b34a6e7fe4e8fcb0e8cf0d82',1,'vinecopulib::Vinecop::Vinecop(const char *filename, bool check_matrix=true)'],['../classvinecopulib_1_1_vinecop.html#a899449d750e92e220dda904287b39b07',1,'vinecopulib::Vinecop::Vinecop(boost::property_tree::ptree input, bool check_matrix=true)']]],
  ['vinecop',['Vinecop',['../classvinecopulib_1_1_vinecop.html',1,'vinecopulib']]],
  ['vinecopulib',['vinecopulib',['../namespacevinecopulib.html',1,'']]]
];
