"""Generate the analytic derivative leaves for the BB and Tawn bicop families.

Each requested selector is expanded from the verified symbolic assembly
(``assembly.py``), CSE'd, and emitted as a C++ closed form into the family's
``.ipp`` between the ``[BEGIN/END generated derivative leaves]`` markers. Run
from the repo root:  ``python3 tools/derivs/generate.py [family ...]``.

The generated code is fast (hand-coded style) but machine-produced; do not edit
it by hand. Correctness is gated by ``derivatives_match_finite_differences`` in
the test suite (analytic vs. central finite differences); this script also
asserts that its power-rewrite is an exact identity.
"""
import os
import re
import shutil
import subprocess
import sys
import sympy as sp

sys.path.insert(0, os.path.dirname(__file__))
import assembly as asm  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
INC = os.path.join(ROOT, 'include/vinecopulib/bicop')
z, th, de = sp.symbols('z theta delta', positive=True)
u, v, w = asm.u, asm.v, asm.w

# Short, column-0, sub-80-col markers so clang-format leaves them byte-stable
# (a wrapped/dedented marker would break the idempotent re-splice below).
BEGIN = '// [BEGIN generated derivative leaves]'
END = '// [END generated derivative leaves]'
HEADER = ('// Generated by tools/derivs/generate.py from the BB/Tawn derivative\n'
          '// calculus; do not edit by hand (regenerate instead).\n'
          '// ponytail: interior-parameter forms. Boundary singularities are clamped\n'
          '// (not taken to their exact limits) in each leaf head: BB8 delta->1,\n'
          '// Tawn psi_i->0, BB1 theta->0. Upgrade path: emit the continuous-limit\n'
          '// branches per tools/derivs/bb_tawn_analytic_derivatives.tex.\n')


# ---------------------------------------------------------------------------
# emission helpers
# ---------------------------------------------------------------------------
def cxx(e, smap):
    s = sp.ccode(e.subs(smap))
    for fn in ('pow', 'log', 'exp', 'sqrt'):
        s = s.replace(fn + '(', 'std::' + fn + '(')
    return s


def lower_int_pows(code):
    pat = re.compile(r'std::pow\(([A-Za-z_][A-Za-z0-9_]*), (\d+)\)')
    rep = lambda m: '(' + '*'.join([m.group(1)] * int(m.group(2))) + ')' if 2 <= int(m.group(2)) <= 4 else m.group(0)
    prev = None
    while prev != code:
        prev = code
        code = pat.sub(rep, code)
    return code


def make_body(rewrite, check, head, preamble, smap):
    def body(expr):
        check(expr)
        reps, red = sp.cse([rewrite(expr)], symbols=sp.numbered_symbols('t'))
        temps = [(sp.ccode(s), cxx(e, smap)) for s, e in reps]
        ret = cxx(red[0], smap)
        # drop unused CSE temporaries (sympy.cse occasionally leaves one) so the
        # generated code is -Wunused-variable clean; reverse pass for transitivity.
        used = set(re.findall(r'\bt\d+\b', ret))
        kept = []
        for name, rhs in reversed(temps):
            if name in used:
                kept.append((name, rhs))
                used.update(re.findall(r'\bt\d+\b', rhs))
        L = list(head) + ['      ' + ln for ln in preamble]
        L += ['      double %s = %s;' % (n, r) for n, r in reversed(kept)]
        L.append('      return %s;' % ret)
        return lower_int_pows('\n'.join(L))
    return body


def leaf(method, klass, branches, body, route_u2=False, fallback=None):
    L = ['  inline Eigen::VectorXd']
    pad = ' ' * (2 + len(klass) + 2 + len(method) + 1)
    L.append('  %s::%s(const Eigen::MatrixXd& u,' % (klass, method))
    L.append('%sconst Eigen::MatrixXd& parameters,' % pad)
    L.append('%sconst std::string& deriv)' % pad)
    L.append('  {')
    if route_u2:
        L.append('    if (tools_deriv::is_u2_only(deriv))')
        L.append('      return %s(' % method)
        L.append('        tools_eigen::swap_cols(u), parameters, tools_deriv::swap_args(deriv));')
    first = True
    for sel, expr in branches:
        L.append('    %s (deriv == "%s") {' % ('if' if first else 'else if', sel))
        first = False
        L.append('      auto f = [](const double& u1,')
        L.append('                  const double& u2,')
        L.append('                  const Eigen::Ref<const Eigen::VectorXd>& par) {')
        L.append(body(expr))
        L.append('      };')
        L.append('      return tools_eigen::binaryExpr_or_nan(u, parameters, f);')
        L.append('    }')
    # logpdf leaves are only called with parameter selectors; anything else
    # (argument selectors) falls back to the base quotient-rule composition.
    L.append('    ' + (fallback or
                       'throw std::runtime_error("unexpected derivative selector: " + deriv);'))
    L.append('  }')
    return '\n'.join(L)


def splice(ipp_path, generated, splice_anchor):
    src = open(ipp_path).read()
    block = BEGIN + '\n' + HEADER + '\n' + generated + '\n\n' + END + '\n\n'
    # match on the stable marker prefix (not the exact constants) so a re-run
    # replaces the region regardless of clang-format wrapping/indentation or
    # older marker wording -- keeps regeneration idempotent.
    marker_re = re.compile(
        r'//\s*\[BEGIN generated derivative leaves.*?'
        r'//\s*\[END generated derivative leaves\]\n+', re.S)
    if marker_re.search(src):
        src = marker_re.sub(lambda _: block, src, count=1)
    else:
        pos = re.search(splice_anchor, src).start() + 1
        src = src[:pos] + block + src[pos:]
    open(ipp_path, 'w').write(src)


def ensure_decls(hpp_path, ipp_name, methods, anchor):
    src = open(hpp_path).read()
    if 'pdf_deriv_raw' in src:
        return
    decls = '\n  // analytic derivatives (per-selector closed forms; see %s)\n' % ipp_name
    for m in methods:
        decls += ('  Eigen::VectorXd %s(const Eigen::MatrixXd& u,\n'
                  '  %sconst Eigen::MatrixXd& parameters,\n'
                  '  %sconst std::string& deriv);\n\n' % (m, ' ' * (len(m) + 1), ' ' * (len(m) + 1)))
    ins = re.search(anchor, src, flags=re.S).end()
    open(hpp_path, 'w').write(src[:ins] + decls + src[ins:])


ARCHI_METHODS = ['pdf_deriv_raw', 'pdf_deriv2_raw', 'hfunc1_deriv_raw',
                 'hfunc1_deriv2_raw', 'logpdf_deriv_raw', 'logpdf_deriv2_raw']
EV_METHODS = ARCHI_METHODS + ['hfunc2_deriv_raw', 'hfunc2_deriv2_raw']
LOGPDF_FALLBACK1 = 'return AbstractBicop::logpdf_deriv_raw(u, parameters, deriv);'
LOGPDF_FALLBACK2 = 'return AbstractBicop::logpdf_deriv2_raw(u, parameters, deriv);'


# ---------------------------------------------------------------------------
# Archimedean families (BB1/6/7/8)
# ---------------------------------------------------------------------------
def make_archi_rewriter(base_fn, base_sign):
    Pu, Pv, Pw = sp.symbols('Pu Pv Pw', positive=True)
    bases = {u: base_fn.subs(z, u), v: base_fn.subs(z, v), w: base_fn.subs(z, w)}
    ps = {bases[u]: Pu, bases[v]: Pv, bases[w]: Pw}

    def rewrite(e):
        def f(pw):
            b, ex = pw.as_base_exp()
            a = sp.simplify(ex.coeff(th))
            return ps[b]**(a / base_sign) * b**sp.simplify(ex - a * th)
        return e.replace(lambda x: x.is_Pow and x.as_base_exp()[0] in ps, f)

    def check(e):
        back = rewrite(e).subs({Pu: bases[u]**(base_sign * th), Pv: bases[v]**(base_sign * th),
                                Pw: bases[w]**(base_sign * th)})
        pt = {u: sp.Rational(37, 100), v: sp.Rational(61, 100), w: sp.Rational(29, 100),
              th: sp.Rational(17, 10), de: sp.Rational(13, 10)}
        assert abs(complex((back - e).subs(pt).evalf(30))) < 1e-18, 'rewrite identity FAIL'

    return rewrite, check


def archimedean_family(spec):
    A = asm.archimedean(spec['phi'])
    rewrite, check = make_archi_rewriter(spec['base_fn'], spec['base_sign'])
    smap = {u: sp.Symbol('u1'), v: sp.Symbol('u2')}
    head = spec.get('head', ['      double theta = par(0), delta = par(1);'])
    body = make_body(rewrite, check, head, spec['preamble'], smap)
    X = {'par1': 2, 'par2': 3, 'u1': 0, 'u2': 1}
    K = spec['klass']

    def mk(fn, sels):
        out = []
        for s in sels:
            comps = re.findall(r'par\d|u\d', s)
            out.append((s, A[fn](*[X[c] for c in comps])))
        return out

    parts = [
        leaf('pdf_deriv_raw', K, mk('c_d1', ['par1', 'par2', 'u1']), body, route_u2=True),
        leaf('pdf_deriv2_raw', K, mk('c_d2', ['par1par1', 'par1par2', 'par2par2', 'par1u1',
                                              'par2u1', 'u1u1', 'u1u2']), body, route_u2=True),
        leaf('hfunc1_deriv_raw', K, mk('h1_d1', ['par1', 'par2', 'u1']), body),
        leaf('hfunc1_deriv2_raw', K, mk('h1_d2', ['par1par1', 'par1par2', 'par2par2', 'par1u1',
                                                  'par2u1', 'u1u1']), body),
        leaf('logpdf_deriv_raw', K, mk('logc_d1', ['par1', 'par2']), body, fallback=LOGPDF_FALLBACK1),
        leaf('logpdf_deriv2_raw', K, mk('logc_d2', ['par1par1', 'par1par2', 'par2par2']), body,
             fallback=LOGPDF_FALLBACK2),
    ]
    return ('\n\n'.join(parts), ARCHI_METHODS, r'  Eigen::VectorXd pdf_raw\([^;]*?\);\n',
            r'\ninline [^\n]*\n\w+::parameters_to_tau')


# ---------------------------------------------------------------------------
# Extreme-value family (Tawn)
# ---------------------------------------------------------------------------
def tawn_family(spec):
    A = asm.extreme_value(spec['A'])
    rewrite = lambda e: e
    check = lambda e: None
    smap = {u: sp.Symbol('u1'), v: sp.Symbol('u2'), asm.r_s: sp.Symbol('r'),
            asm.t_s: sp.Symbol('t'), asm.p1: sp.Symbol('psi1'), asm.p2: sp.Symbol('psi2'),
            asm.pth: sp.Symbol('theta')}
    # clamp psi_i off 0: the interior forms have 1/psi and psi^theta*log(psi)
    # that are NaN at the psi=0 lower bound (see the note's boundary remark).
    head = ['      double psi1 = std::fmax(par(0), 1e-10), '
            'psi2 = std::fmax(par(1), 1e-10), theta = par(2);']
    preamble = ['double r = -std::log(u1 * u2);',
                'double t = std::log(u2) / std::log(u1 * u2);']
    body = make_body(rewrite, check, head, preamble, smap)
    K = spec['klass']
    X = {'par1': 2, 'par2': 3, 'par3': 4, 'u1': 0, 'u2': 1}

    def mk(fn, sels):
        out = []
        for s in sels:
            comps = re.findall(r'par\d|u\d', s)
            out.append((s, A[fn](*[X[c] for c in comps])))
        return out

    pars = ['par1', 'par2', 'par3']
    par_pairs = ['par1par1', 'par1par2', 'par1par3', 'par2par2', 'par2par3', 'par3par3']
    parts = [
        leaf('pdf_deriv_raw', K, mk('c_d1', pars + ['u1', 'u2']), body),
        leaf('pdf_deriv2_raw', K, mk('c_d2', par_pairs
             + ['par1u1', 'par2u1', 'par3u1', 'par1u2', 'par2u2', 'par3u2', 'u1u1', 'u1u2', 'u2u2']), body),
        leaf('hfunc1_deriv_raw', K, mk('h1_d1', pars + ['u1']), body),
        leaf('hfunc1_deriv2_raw', K, mk('h1_d2', par_pairs + ['par1u1', 'par2u1', 'par3u1', 'u1u1']), body),
        leaf('hfunc2_deriv_raw', K, mk('h2_d1', pars + ['u2']), body),
        leaf('hfunc2_deriv2_raw', K, mk('h2_d2', par_pairs + ['par1u2', 'par2u2', 'par3u2', 'u2u2']), body),
        leaf('logpdf_deriv_raw', K, mk('logc_d1', pars), body, fallback=LOGPDF_FALLBACK1),
        leaf('logpdf_deriv2_raw', K, mk('logc_d2', par_pairs), body, fallback=LOGPDF_FALLBACK2),
    ]
    return ('\n\n'.join(parts), EV_METHODS, r'pickands_derivative2\([^;]*?;',
            r'\ninline [^\n]*\nTawnBicop::get_start_parameters')


# ---------------------------------------------------------------------------
# family specs
# ---------------------------------------------------------------------------
_A_tawn = ((1 - asm.p1) * (1 - asm.t_s) + (1 - asm.p2) * asm.t_s
           + ((asm.p2 * asm.t_s)**asm.pth + (asm.p1 * (1 - asm.t_s))**asm.pth)**(1 / asm.pth))

FAMILIES = {
    'bb1': dict(kind='archi', klass='Bb1Bicop', phi=(z**(-th) - 1)**de, base_fn=z, base_sign=-1,
                head=['      double theta = std::fmax(par(0), 1e-10), delta = par(1);'],
                preamble=[
                    'double Pu = std::pow(u1, -theta), Pv = std::pow(u2, -theta);',
                    'double su = std::pow(Pu - 1.0, delta), sv = std::pow(Pv - 1.0, delta);',
                    'double w = std::pow(std::pow(su + sv, 1.0 / delta) + 1.0, -1.0 / theta);',
                    'double Pw = std::pow(w, -theta);']),
    'bb6': dict(kind='archi', klass='Bb6Bicop', phi=(-sp.log(1 - (1 - z)**th))**de, base_fn=1 - z, base_sign=1,
                preamble=[
                    'double Pu = std::pow(1.0 - u1, theta), Pv = std::pow(1.0 - u2, theta);',
                    'double su = std::pow(-tools_stl::log1p(-Pu), delta), sv = std::pow(-tools_stl::log1p(-Pv), delta);',
                    'double w = 1.0 - std::pow(-std::expm1(-std::pow(su + sv, 1.0 / delta)), 1.0 / theta);',
                    'double Pw = std::pow(1.0 - w, theta);']),
    'bb7': dict(kind='archi', klass='Bb7Bicop', phi=(1 - (1 - z)**th)**(-de) - 1, base_fn=1 - z, base_sign=1,
                preamble=[
                    'double Pu = std::pow(1.0 - u1, theta), Pv = std::pow(1.0 - u2, theta);',
                    'double su = std::pow(1.0 - Pu, -delta) - 1.0, sv = std::pow(1.0 - Pv, -delta) - 1.0;',
                    'double w = 1.0 - std::pow(1.0 - std::pow(1.0 + su + sv, -1.0 / delta), 1.0 / theta);',
                    'double Pw = std::pow(1.0 - w, theta);']),
    'bb8': dict(kind='archi', klass='Bb8Bicop', phi=-sp.log((1 - (1 - de * z)**th) / (1 - (1 - de)**th)),
                base_fn=1 - de * z, base_sign=1,
                head=['      double theta = par(0), delta = std::fmin(par(1), 1.0 - 1e-10);'],
                preamble=[
                    'double kappa = 1.0 - std::pow(1.0 - delta, theta);',
                    'double Pu = std::pow(1.0 - delta * u1, theta), Pv = std::pow(1.0 - delta * u2, theta);',
                    'double su = -std::log((1.0 - Pu) / kappa), sv = -std::log((1.0 - Pv) / kappa);',
                    'double w = (1.0 - std::pow(1.0 + std::exp(-(su + sv)) * (std::pow(1.0 - delta, theta) - 1.0), 1.0 / theta)) / delta;',
                    'double Pw = std::pow(1.0 - delta * w, theta);']),
    'tawn': dict(kind='ev', klass='TawnBicop', A=_A_tawn),
}


def clang_format(*paths):
    exe = shutil.which('clang-format-14') or shutil.which('clang-format')
    if exe:
        subprocess.run([exe, '-i', *paths], check=True)


def main():
    names = sys.argv[1:] or list(FAMILIES.keys())
    for nm in names:
        spec = FAMILIES[nm]
        print('generating %s ...' % nm, flush=True)
        gen, methods, anchor, splice_anchor = (tawn_family(spec) if spec['kind'] == 'ev'
                                               else archimedean_family(spec))
        ipp = os.path.join(INC, 'implementation/%s.ipp' % nm)
        hpp = os.path.join(INC, '%s.hpp' % nm)
        splice(ipp, gen, splice_anchor)
        ensure_decls(hpp, '%s.ipp' % nm, methods, anchor)
        clang_format(ipp, hpp)
        print('  pow=%d log=%d lines=%d' % (gen.count('std::pow('), gen.count('std::log('),
                                            gen.count(chr(10)) + 1), flush=True)


if __name__ == '__main__':
    main()
