message( STATUS )
message( STATUS "------------------ General configuration for ${PROJECT_NAME} ${PROJECT_VERSION}")
message( STATUS )
message( STATUS "CMAKE_SYSTEM_PROCESSOR:        ${CMAKE_SYSTEM_PROCESSOR}" )
message( STATUS "Generator:                     ${CMAKE_GENERATOR}")
message( STATUS "CMAKE_SYSTEM_VERSION:          ${CMAKE_SYSTEM_VERSION}")
message( STATUS "CMAKE_CXX_COMPILER_ID:         ${CMAKE_CXX_COMPILER_ID}")
message( STATUS "CMAKE_CXX_COMPILER:            ${CMAKE_CXX_COMPILER}")
message( STATUS "CMAKE_CXX_COMPILER_VERSION:    ${CMAKE_CXX_COMPILER_VERSION}")
message( STATUS )
message( STATUS "CMAKE_BUILD_TYPE:              ${CMAKE_BUILD_TYPE}")
get_directory_property(global_definitions COMPILE_DEFINITIONS)
message(STATUS "Global compile definitions:    ${global_definitions}")
message( STATUS "CMAKE_CXX_FLAGS:               ${CMAKE_CXX_FLAGS}")
message( STATUS "CMAKE_CXX_FLAGS_DEBUG:         ${CMAKE_CXX_FLAGS_DEBUG}")
message( STATUS "CMAKE_CXX_FLAGS_RELEASE:       ${CMAKE_CXX_FLAGS_RELEASE}")
message( STATUS )
message( STATUS "BUILD_TESTING:                 ${BUILD_TESTING}")
message( STATUS "VINECOPULIB_SHARED_LIB:        ${VINECOPULIB_SHARED_LIB}")
message( STATUS "OPT_ASAN:                      ${OPT_ASAN}")
message( STATUS "STRICT_COMPILER:               ${STRICT_COMPILER}")
message( STATUS "CODE_COVERAGE:                 ${CODE_COVERAGE}")
message( STATUS "BUILD_DOC:                     ${BUILD_DOC}")
message( STATUS )